http:
  port: "8081"
  
sfdc:
  username: "pavani@techbulls.com"
  password: "lakshmi@8"
  token: "M33d9uHawt4PbTHREkrneNo7r"
  
file:
   accountsDir: "C:/Users/hiiii/Downloads/APDevFundamentals4.4_studentFiles_SP_27jun2022/APDevFundamentals4.4_studentFiles_SP_27jun2022/resources"
   
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"